name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK 
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x

      - name: Install dependencies
        run: dotnet restore rsoi_lr1.sln

      - name: Build
        run: dotnet publish rsoi_lr1/rsoi_lr1/rsoi_lr1.csproj -c Release -o publish --no-restore

      - name: Test
        run:  dotnet test rsoi_lr1/rsoi_test_lr1/rsoi_test_lr1.csproj --no-restore

      - name: Deploy project
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: "e53782e3-2850-4334-94dc-8c60fb0a0f6c"
          heroku_app_name: rsoi13
          heroku_email: alina_sartlanova@mail.ru
          usedocker: true

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
